### ISSUE TITLE
Need to reset heroku repo to deploy new version

### ISSUE THREAD

**Issue by calleo** [metabase/metabase-heroku#6]
Hi,

Metabase is running on Heroku. When we upgrade, it's not enough to just push this code to the Heroku repo again:

> ->metabase-deploy git:(master) git remote -v    
> heroku	https://git.heroku.com/woo-kpi-prod.git (fetch)
> heroku	https://git.heroku.com/woo-kpi-prod.git (push)
> origin	https://github.com/metabase/metabase-deploy.git (fetch)
> origin	https://github.com/metabase/metabase-deploy.git (push)
> ->metabase-deploy git:(master) git pull origin
> Already up-to-date.
> ->metabase-deploy git:(master) git push -f heroku master
> Everything up-to-date

Heroku seems to believe that nothing has changed, so if refuses to re-deploy.

Currently, the workaround is to reset the repo using: https://github.com/heroku/heroku-repo, then pushing to the Heroky repo again.

Perhaps there is a better way of doing this? If it's not possible to fix this problem from Metabase side, I think it would be a good idea to mention it in the docs.

**Comment by salsakran** [comment]
Please note the first line of the readme, and use the buildpack in the docs (github.com/metabase/metabase-buildpack). 

This repo is NOT YET MEANT TO BE USED. The docs and the website (www.metabase.com) are the authoritative sources. We can and will have randomly named repos that aren't ready for primetime.

**Comment by calleo** [comment]
Oops, ended up in the wrong repo. However the issue remains. I'll post it in metabase/metabase.
